// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plhddnoannqqsqpvfxxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsaGRkbm9hbm5xcXNxcHZmeHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjczMjUsImV4cCI6MjA2NDk0MzMyNX0.gcRIs2Arnz3jFvoGNsdR5G-PfAV1tPI0tltAJRSs644";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);